### ISSUE TITLE
CREATE MATERIALIZED VIEW query ends with error at Clickhousex.Codec.JSON

### ISSUE THREAD

**Issue by sofakingworld** [appodeal/clickhousex#18]
Create materialized view fails on execution
```elixir
q  = """
    CREATE MATERIALIZED VIEW IF NOT EXISTS some_view
    ENGINE = MergeTree() ORDER BY number
    AS SELECT 
    number 
    FROM system.numbers
"""
Clickhousex.query(:clickhouse, q, [])

** (CaseClauseError) no case clause matching: {:error, %Jason.DecodeError{data: "", position: 0, token: nil}}
    (clickhousex) lib/clickhousex/codec/json.ex:18: Clickhousex.Codec.JSON.decode/1
    (clickhousex) lib/clickhousex/http_client.ex:39: Clickhousex.HTTPClient.send_p/5
    (clickhousex) lib/clickhousex/protocol.ex:134: Clickhousex.Protocol.do_query/4
    (db_connection) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
    (db_connection) lib/db_connection.ex:532: DBConnection.prepare_execute/4
```

Clickhousex version: 0.4.0
Elixir: 1.9.4

**Comment by hissssst** [comment]
Merged #19
