### ISSUE TITLE
CaseClauseError on empty string returned by clickhouse

### ISSUE THREAD

**Issue by florius0** [appodeal/clickhousex#43]
While using json codec and clickhouse returns non-empty string everything is ok.

```elixir
iex(1)> {:ok, pid} = Clickhousex.start_link(scheme: :http, hostname: ...)
{:ok, #PID<0.391.0>}
iex(2)> Clickhousex.query(pid, "SELECT 1", [])
{:ok,
 %Clickhousex.Query{
   columns: [],
   name: "",
   param_count: 0,
   params: [],
   statement: "SELECT 1",
   type: :select
 },
 %Clickhousex.Result{
   columns: ["1"],
   command: :selected,
   num_rows: 1,
   rows: [{1}]
 }}
```

But if clickhouse returns empty string error occurs.

```elixir 
iex(3)> Clickhousex.query(pid, "SHOW TABLES", [])
** (CaseClauseError) no case clause matching: {:error, %Jason.DecodeError{data: "", position: 0, token: nil}}
    (clickhousex 0.5.0) lib/clickhousex/codec/json.ex:38: Clickhousex.Codec.JSON.decode/1
    (clickhousex 0.5.0) lib/clickhousex/http_client.ex:112: Clickhousex.HTTPClient.decode_response/3
    (clickhousex 0.5.0) lib/clickhousex/protocol.ex:167: Clickhousex.Protocol.do_query/5
    (db_connection 2.4.0) lib/db_connection/holder.ex:325: DBConnection.Holder.holder_apply/4
    (db_connection 2.4.0) lib/db_connection.ex:1314: DBConnection.run_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:1409: DBConnection.run/6
    (db_connection 2.4.0) lib/db_connection.ex:574: DBConnection.parsed_prepare_execute/5
    (db_connection 2.4.0) lib/db_connection.ex:566: DBConnection.prepare_execute/4
```

**Comment by hissssst** [comment]
Can't reproduce. What version of Clickhouse were you using?

This query
```sql
SHOW TABLES
```

Returns table with column `count`

**Comment by florius0** [comment]
Can't remember right now, it might have been clickhouse bug.
